Implemented all requirements.
cudabanger/PFMCPP_Project8 pull request #1
Opened 2021-08-30 20:46 UTC by cudabanger

2021-08-30 22:05 UTC, matkatmusic requested changes
In addition to the things I've marked below, You didn't implement `HighwayPatrol::30`

2021-08-30 22:05 UTC, matkatmusic commented on Car.h
>  struct Car : public Vehicle
```    
    10) correct any unnecessary keywords related to access specifiers used in the UDTs.
```
- [x] revise

2021-08-30 22:05 UTC, matkatmusic commented on Highway.cpp
> +    }
1) use `else if`.  you're currently checking if `v` is a `Motorcycle*`, even if it's already been determined to be a `Car*`.
2) you need to write a function in `SemiTruck`.  Don't call `setSpeed` here.

- [x] revise

2021-08-30 22:05 UTC, matkatmusic commented on Highway.cpp
> +    }
1) use `else if`. 
2) "trucks pull over".   Think back to Project 1, where you came up with plain-english expressions and wrote pseudo-code that did the same thing.   Apply that concept here.
- [x] revise

2021-08-30 22:05 UTC, matkatmusic commented on HighwayPatrol.cpp
> +HighwayPatrol::~HighwayPatrol()
Correct!

2021-08-30 22:05 UTC, matkatmusic commented on HighwayPatrol.h
> +struct HighwayPatrol : public Vehicle
```    
    10) correct any unnecessary keywords related to access specifiers used in the UDTs.
```
- [x] revise

2021-08-30 22:05 UTC, matkatmusic commented on Motorcycle.h
>  struct Motorcycle : public Vehicle
```    
    10) correct any unnecessary keywords related to access specifiers used in the UDTs.
```
- [x] revise

2021-08-30 22:05 UTC, matkatmusic commented on SemiTruck.cpp
> +}
The internals of this function are the exact opposite of `trying to evade`. 
name things what they do.  This truck has pulled over.
- [x] revise

2021-08-30 22:05 UTC, matkatmusic commented on SemiTruck.cpp
> +}
it's pointless to override the base class function and only call the base class function from the derived function.  The only thing this does is add more function calls to the call stack, which adds bloat in the compiled binary. 
```
   5) Add a Truck type
        semi-trucks don't evade when they're pulled over, unlike cars and motorcycles.  
        They'll also need a member function that can be called when they are added to the highway.  Look at the Highway member functions for more hints on this.
```
- [x] revise

2021-08-30 22:05 UTC, matkatmusic commented on SemiTruck.h
> +struct SemiTruck : public Vehicle
```
  10) correct any unnecessary keywords related to access specifiers used in the UDTs
```
- [x] revise

2021-08-30 22:05 UTC, matkatmusic commented on SemiTruck.h
> +    void setSpeed(int s) override;
```
        semi-trucks don't evade when they're pulled over, unlike cars and motorcycles.  
        They'll also need a member function that can be called when they are added to the highway.  Look at the Highway member functions for more hints on this.
```
- [ ] revise

2021-08-30 22:18 UTC, cudabanger commented on HighwayPatrol.cpp
> +HighwayPatrol::~HighwayPatrol()
I don't get it.  Are you acknowledging my comment?  The code following it *is* the out-of-line code so what is it that you want me to do here?

2021-08-31 01:20 UTC, matkatmusic requested changes

2021-08-31 01:20 UTC, matkatmusic commented on HighwayPatrol.cpp
> +        std::cout << name << ": YOU IN THE " << v->name << " PULL OVER AND SHOW YOUR HANDS" << std::endl;
`v->name` is not the `vehicle type`.
- [ ] revise

2021-08-31 01:20 UTC, matkatmusic commented on SemiTruck.cpp
> +}
add a `std::cout` statement to this function. 
- [ ] revise

2021-08-31 03:49 UTC, matkatmusic approved these changes

2021-08-31 03:49 UTC, merged